spring.application.name=MenaAndFeena_FinalProject

#spring.datasource.url=jdbc:mysql://localhost:3306/bank_system_payment

#spring.datasource.username=root

#spring.datasource.password=

##spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.jpa.show-sql=true

#spring.jpa.generate-ddl=true

#create-drop كل ما شغلت السيرفر يسوي كرييت دروب
#اذا بينهم رليشن اخليه ابديتد
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update


#spring.web.error.include-message=always

#spring.web.error.include-stacktrace=always


# استبدل xxxxxxxxxxxxxxxx بمفتاحك السري الحقيقي من لوحة تحكم ميسر
moyasar.api.key=sk_test_vwZMnsaybbE7nxPisywnxztKpqh2strgaamDTbyJ



server.port= 5000

#JDBC URL for connecting to the MySQL database hosted on Amazon RDS.

#Format: jdbc:mysql://<hostname>:<port>/<database_name>

spring.datasource.url=jdbc:mysql://database-1.cvu6eus6k2p4.eu-central-1.rds.amazonaws.com:3306/SimpleShop
spring.datasource.username=Reenad
spring.datasource.password=Ren3011h.

#The username to authenticate with the database.

#spring.datasource.username= Reenad

#The password to authenticate with the database.

#spring.datasource.password= Ren3011h.

#The fully qualified class name of the MySQL JDBC driver used for database connectivity.

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate setting to define the action for schema generation.

#update ensures the schema is automatically updated based on the entity definitions in the code.

spring.jpa.hibernate.ddl-auto=update

#When set to 'true', all SQL statements executed by the application are printed to the logs.

#Enables SQL query logging in the console.

spring.jpa.show-sql=true


# ===================================================================
# REAL EMAIL INTEGRATION
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===================================================================
# REAL WHATSAPP INTEGRATION
# ===================================================================
ultramsg.instance.id=${ULTRMSG_INSTANCE_ID}
ultramsg.token=${ULTRMSG_TOKEN}

# =========================
# OPENAI CONFIG
# =========================

openai.api.url=https://api.openai.com
openai.api.key=${OPENAI_API_KEY}

