spring.application.name=MenaAndFeena_FinalProject


spring.datasource.url=jdbc:mysql://localhost:3306/menaandfeena

spring.datasource.username=root

spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



spring.jpa.show-sql=true

spring.jpa.generate-ddl=true

spring.jpa.hibernate.ddl-auto=update



spring.web.error.include-message=always

spring.web.error.include-stacktrace=always

# ===================================================================
# REAL EMAIL INTEGRATION
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
app.support.email=reenad0almadi@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===================================================================
# REAL WHATSAPP INTEGRATION
# ===================================================================
ultramsg.instance.id=${ULTRMSG_INSTANCE_ID}
ultramsg.token=${ULTRMSG_TOKEN}

# =========================
# OPENAI CONFIG
# =========================

openai.api.url=https://api.openai.com
openai.api.key=${OPENAI_API_KEY}


#moyasar.api.key=sk_test_1234567890demoKeyHere


moyasar.api.key=sk_test_jvnwxaMdg6Eo9jP3sXJTTPMywMqq85XdsXqtdKQU

app.upload.dir=uploads


jwt.secret=ManaWaFinaSecretKeyManaWaFinaSecretKey2026
jwt.expiration=86400000



